version: '2'
services:
   S_OpenLDAP:
       image: osixia/openldap
       command: --copy-service
       container_name: C_OpenLDAP
       ports:
           - 389:389
           - 689:689
       volumes:
           - ldap_config:/etc/ldap/slapd.d
           - ldap_database:/var/lib/ldap
#           - ./en_populate.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50_en_populate.ldif
       environment:
#  login DN: cn=admin,dc=kanodomain
           LDAP_DOMAIN: "kanodomain"
           LDAP_ORGANISATION: "KanoSoftware"
           LDAP_ADMIN_PASSWORD: "<K@nomdm"
           LDAP_CONFIG_PASSWORD: "<K@nomdm"
           LDAP_READONLY_USER: "true"
           LDAP_READONLY_USER_USERNAME: "ro-user"
           LDAP_READONLY_USER_PASSWORD: "ro-user"
#	env_file:
#           - .env_OpenLDAP
#   networks:
#   restart: unless-stopped

   S_PhpLDAPAdmin:
       image: osixia/phpldapadmin
       container_name: C_PhpLDAPAdmin
       environment:
            PHPLDAPADMIN_LDAP_HOSTS: S_OpenLDAP
       links:
           - S_OpenLDAP
       depends_on:
           - S_OpenLDAP
       ports:
           - 6443:443

volumes:
   ldap_config:
   ldap_database:


